# Generated by Django 5.2.17 on 2026-08-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='Mohammad Hasan Kaman', max_length=120)),
                ('name_fa', models.CharField(default='محمد حسن کمان', max_length=120)),
                ('name_ar', models.CharField(default='محمد حسن كمان', max_length=120)),
                ('role_en', models.CharField(default='Full-Stack Developer', max_length=200)),
                ('role_fa', models.CharField(default='توسعه\u200cدهنده فول\u200cاستک', max_length=200)),
                ('role_ar', models.CharField(default='مطور برمجيات متكاملة', max_length=200)),
                ('tagline_en', models.TextField(blank=True)),
                ('tagline_fa', models.TextField(blank=True)),
                ('tagline_ar', models.TextField(blank=True)),
                ('about_en', models.TextField(blank=True)),
                ('about_fa', models.TextField(blank=True)),
                ('about_ar', models.TextField(blank=True)),
                ('email', models.EmailField(default='kaman.hasan.dev@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('location_en', models.CharField(default='Germany (Remote)', max_length=120)),
                ('location_fa', models.CharField(default='آلمان (دورکاری)', max_length=120)),
                ('location_ar', models.CharField(default='ألمانيا (عن بُعد)', max_length=120)),
                ('github', models.URLField(default='https://github.com/Mohammad-Hasan-Kaman')),
                ('linkedin', models.URLField(default='https://www.linkedin.com/in/kaman-programmer/')),
                ('twitter', models.URLField(default='https://x.com/kaman_hasan0975')),
                ('telegram', models.URLField(default='https://t.me/mohaka0975')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('years_experience', models.PositiveIntegerField(default=4)),
                ('projects_completed', models.PositiveIntegerField(default=15)),
                ('happy_clients', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=160)),
                ('title_fa', models.CharField(blank=True, max_length=160)),
                ('title_ar', models.CharField(blank=True, max_length=160)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description_en', models.TextField()),
                ('description_fa', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ai', 'AI & Developer Tools'), ('web', 'Web Platforms'), ('security', 'Security & Networking'), ('desktop', 'Desktop & Bots')], default='ai', max_length=20)),
                ('icon', models.CharField(default='🚀', help_text='Emoji shown on the project card', max_length=10)),
                ('tech_stack', models.CharField(help_text='Comma-separated, e.g. Python, Django, SQLite', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('live_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False, help_text='Featured projects appear larger on the home page')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-featured', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='💡', help_text='Emoji', max_length=10)),
                ('title_en', models.CharField(max_length=140)),
                ('title_fa', models.CharField(blank=True, max_length=140)),
                ('title_ar', models.CharField(blank=True, max_length=140)),
                ('description_en', models.TextField()),
                ('description_fa', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('level', models.PositiveIntegerField(default=85, help_text='Percent 0-100')),
                ('icon', models.CharField(blank=True, help_text='Emoji (optional)', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role_en', models.CharField(blank=True, max_length=140)),
                ('role_fa', models.CharField(blank=True, max_length=140)),
                ('role_ar', models.CharField(blank=True, max_length=140)),
                ('text_en', models.TextField()),
                ('text_fa', models.TextField(blank=True)),
                ('text_ar', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
