# Generated by Django 5.2.17 on 2026-08-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document',
            field=models.FileField(blank=True, help_text='PDF/document describing this project (shown as download for confidential projects).', null=True, upload_to='project_docs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='Show in the dedicated Confidential Projects section instead of the public grid (source code cannot be shared for financial/business reasons).', verbose_name='Confidential project'),
        ),
    ]
