# Generated by Django 5.2.17 on 2026-08-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_document_project_is_confidential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=220)),
                ('title_fa', models.CharField(blank=True, max_length=220)),
                ('title_ar', models.CharField(blank=True, max_length=220)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('icon', models.CharField(default='📝', help_text='Emoji shown on the article card', max_length=10)),
                ('excerpt_en', models.TextField(blank=True, help_text='Short summary shown on the card')),
                ('excerpt_fa', models.TextField(blank=True)),
                ('excerpt_ar', models.TextField(blank=True)),
                ('body_en', models.TextField(help_text='Full article text (EN). Separate paragraphs with a blank line.')),
                ('body_fa', models.TextField(blank=True)),
                ('body_ar', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Newest first by date; use order to pin items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_confidential',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='mohammadhasankaman@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_ar',
            field=models.CharField(default='محمد حسن كَمَن', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_fa',
            field=models.CharField(default='محمد حسن کَمَن', max_length=120),
        ),
    ]
