# Generated by Django 5.2.17 on 2026-08-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_article_remove_project_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=60)),
                ('name_fa', models.CharField(blank=True, max_length=60)),
                ('name_ar', models.CharField(blank=True, max_length=60)),
                ('level_en', models.CharField(max_length=80)),
                ('level_fa', models.CharField(blank=True, max_length=80)),
                ('level_ar', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CV Language',
                'verbose_name_plural': 'CV Languages',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_en', models.CharField(max_length=200)),
                ('degree_fa', models.CharField(blank=True, max_length=200)),
                ('degree_ar', models.CharField(blank=True, max_length=200)),
                ('institution_en', models.CharField(blank=True, max_length=200)),
                ('institution_fa', models.CharField(blank=True, max_length=200)),
                ('institution_ar', models.CharField(blank=True, max_length=200)),
                ('period_en', models.CharField(blank=True, max_length=80)),
                ('period_fa', models.CharField(blank=True, max_length=80)),
                ('period_ar', models.CharField(blank=True, max_length=80)),
                ('details_en', models.TextField(blank=True, help_text='Relevant studies / highlights (one per line)')),
                ('details_fa', models.TextField(blank=True)),
                ('details_ar', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_fa', models.CharField(blank=True, max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('org_en', models.CharField(blank=True, help_text='Company / client (optional)', max_length=160)),
                ('org_fa', models.CharField(blank=True, max_length=160)),
                ('org_ar', models.CharField(blank=True, max_length=160)),
                ('period_en', models.CharField(blank=True, help_text='e.g. 2024 — Present', max_length=80)),
                ('period_fa', models.CharField(blank=True, max_length=80)),
                ('period_ar', models.CharField(blank=True, max_length=80)),
                ('description_en', models.TextField()),
                ('description_fa', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='summary_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='summary_en',
            field=models.TextField(blank=True, default='Highly motivated and self-taught developer with a strong foundation in Python and JavaScript. Experienced in engineering custom AI-powered applications, backend automation tools and full-stack web solutions, with a passion for solving algorithmic and system-level problems.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='summary_fa',
            field=models.TextField(blank=True),
        ),
    ]
