# Generated by Django 5.2.17 on 2026-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_cvlanguage_education_experience_profile_summary_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='core_competencies_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='core_competencies_en',
            field=models.TextField(blank=True, default='Backend Development & Automation\nAPI Integration & Management\nDatabase Design & Architecture\nAI Application Development\nWeb Application Architecture\nNetwork Infrastructure & Troubleshooting'),
        ),
        migrations.AddField(
            model_name='profile',
            name='core_competencies_fa',
            field=models.TextField(blank=True),
        ),
    ]
