# Generated by Django 5.2.17 on 2026-09-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_profile_core_competencies_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('label', models.CharField(blank=True, help_text='Human-readable hint shown in the admin (auto-filled by seed)', max_length=200)),
                ('value_en', models.TextField(blank=True)),
                ('value_fa', models.TextField(blank=True)),
                ('value_ar', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'UI Text',
                'verbose_name_plural': 'UI Texts (menus, headings, buttons, footer)',
                'ordering': ['key'],
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='period_en',
            field=models.CharField(blank=True, help_text='e.g. 2024 — 2026', max_length=80),
        ),
    ]
