# Generated by Django 5.2.17 on 2026-09-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_marqueetag_sitetext_alter_experience_period_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('pageview', 'Page view'), ('cv_download', 'CV download'), ('contact', 'Contact form'), ('lang_switch', 'Language switch')], default='pageview', max_length=20)),
                ('path', models.CharField(blank=True, db_index=True, max_length=300)),
                ('lang', models.CharField(default='en', max_length=2)),
                ('referrer', models.CharField(blank=True, max_length=400)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=10)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('ip_hash', models.CharField(blank=True, max_length=16)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Visit / event',
                'verbose_name_plural': 'Analytics — visits & events',
                'ordering': ['-created_at'],
            },
        ),
    ]
