# Generated by Django 5.2.17 on 2026-09-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.AddField(
            model_name='skill',
            name='level_ar',
            field=models.CharField(blank=True, help_text='Optional custom label (AR).', max_length=60),
        ),
        migrations.AddField(
            model_name='skill',
            name='level_en',
            field=models.CharField(blank=True, help_text='Optional custom label (EN). Leave blank to use tier default.', max_length=60),
        ),
        migrations.AddField(
            model_name='skill',
            name='level_fa',
            field=models.CharField(blank=True, help_text='Optional custom label (FA).', max_length=60),
        ),
        migrations.AddField(
            model_name='skill',
            name='tier',
            field=models.PositiveIntegerField(choices=[(1, 'Advanced — used in shipped projects'), (2, 'Production experience'), (3, 'Working knowledge')], default=2, help_text='Honest level label — no percentages'),
        ),
    ]
